name: Build, publish, test and containerize to image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: qshu911/amorashop

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Build docker image and push it to docker hub
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build --no-cache -t $DOCKER_IMAGE:$IMAGE_TAG .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push $DOCKER_IMAGE:$IMAGE_TAG
          docker tag $DOCKER_IMAGE:$IMAGE_TAG $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:latest
      
      - name: Pull docker image from docker hub and run on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
              docker stop my-app || true
              docker rm my-app || true
              docker rmi $DOCKER_IMAGE:latest || true
              docker pull $DOCKER_IMAGE:latest
              docker run --name my-app -p 80:80 -d $DOCKER_IMAGE:latest
