name: Build, publish, test and containerize to image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Build docker image and push it to docker hub
        run: |
          docker build -t qshu911/amorashop:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push qshu911/amorashop:latest
      
      - name: Pull docker image from docker hub and run on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
              docker pull --no-cache ${{ secrets.DOCKER_USERNAME }}/amorashop:latest
              docker stop my-app || true
              docker rm my-app || true
              docker run --name my-app -p 80:80 -d ${{ secrets.DOCKER_USERNAME }}/amorashop:latest