name: Build, publish, test and containerize to image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Build docker image and push it to docker hub
        run: |
          IMAGE_TAG=qshu911/amorashop:$(date +%Y%m%d%H%M%S)
          docker build -t $IMAGE_TAG -t qshu911/amorashop:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push $IMAGE_TAG
          docker push qshu911/amorashop:latest
          echo "Image built and pushed: $IMAGE_TAG"
          echo "SHA256 of the pushed image:"
          docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_TAG

      - name: Wait for Docker Hub to update
        run: sleep 30

      - name: Pull docker image from docker hub and run on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
              echo "Removing old image..."
              docker rmi qshu911/amorashop:latest || true
              
              echo "Cleaning up docker system..."
              docker system prune -f

              echo "Pulling new image..."
              docker pull qshu911/amorashop:latest

              echo "Inspecting pulled image..."
              docker inspect qshu911/amorashop:latest

              echo "Stopping and removing existing container..."
              docker stop my-app || true
              docker rm my-app || true
              
              echo "Running new container..."
              docker run --name my-app -p 80:80 -d qshu911/amorashop:latest

              echo "Verifying running container..."
              docker ps
              docker logs my-app
